---
title: "Background"
author: "Garrett Mellinger"
date: "5/21/2026"
format: pdf
---

# Background

We assess whether the 2023 cultural burn is meeting its restoration goals of promoting native grassland species. This study may help to inform future restoration management decisions regarding intentional disturbance at NCOS and could have implications which extend to the management or ecological understanding of other coastal grassland systems. These questions are relevant because Santa Barbara coastal grasslands are fire adapted (Saglimbeni, 2024, pp. 1-2), but are now heavily affected by invasive species. Studying the NCOS burn helps show whether cultural burning can support native species like *Stipa pulchra* while reducing nonnative grassland invaders. The four focal species, *Stipa pulchra*, *Medicago polymorpha*, *Melilotus indicus*, and *Festuca perennis*, were selected because a prior study found these native and non-native species showed contrasting abundance responses to disturbance, making them useful indicators for evaluating changes in grassland composition (Nestor, 2025).

