---
title: "NCOS Mesa Vegetation: Wrangling Brainstorm"
format: pdf
author: Lukas Lescano
date: "2026-05-11"
editor: source
execute: 
  message: false
  warning: false
---

# 1. Set up

## Packages

```{r}
#| label: packages
#| message: false

# general use
library(tidyverse)
library(janitor)

# file organization
library(here)

# data visualization
library(naniar)
library(patchwork)
library(scales)
```

## Data

```{r}
#| label: data

veg <- read_csv(here("data", "raw", "veg.csv"))

metadata <- read_csv(here("data", "raw", "vp_veg_metadata.csv"))
```

# 2. Exploring data structure

```{r}
#| label: explore-structure

glimpse(veg)
glimpse(metadata)
unique(veg)
unique(veg$transect_name)
unique(veg$year)
unique(veg$cover_category)
```

```{r}
#| label: explore-transects

veg |> 
  distinct(transect_name, habitat) |> 
  arrange(transect_name) |> 
  print(n = Inf)
```

```{r}
#| label: explore-grasslands(GL)-peripheral_uplands(PU)

veg |> 
  filter(str_detect(transect_name, "GL|PU")) |> 
  distinct(transect_name, habitat, psoc, cover_category) |> 
  arrange(transect_name, cover_category) |> 
  print(n = Inf)
```

```{r}
#| label: explore-cover-categories

# confirmed cover_category values:
# "NATIVE COVER", "NON-NATIVE COVER", "BARE GROUND", "THATCH", "OTHER COVER"
# for all analyses we will filter to only NATIVE COVER and NON-NATIVE COVER, the rest would be Other

# confirmed clover species codes:
# sweet clover: Melilotus_indicus (and possibly Melilotus_albus (white sweet clover) - check with Garrett)
# bur clover: Medicago_polymorpha

# TODO: get exact transect names for fire-only, sheep-only, fire+sheep plots
```

```{r}
#| label: exploring white sweet clover

#new object from veg
melilotus_albus <- veg |> 
  filter(psoc %in% c("Melilotus_albus",
                     "Melilotus_indicus"))
```

```{r}
#| label: wrangling veg

poaceae_species <- c(
  "Bromus_hordeaceus",
  "Festuca_perennis",
  "Stipa_pulchra",
  "Polypogon_monspeliensis",
  "Brachypodium_distachyon",
  "Festuca_myuros",
  "Avena_barbata",
  "Hordeum_marinum",
  "Avena_fatua",
  "Parapholis_incurva",
  "Bromus_diandrus",
  "Distichlis_spicata",
  "Bromus_catharticus",
  "Hordeum_murinum",
  "Hordeum_brachyantherum_brachy.",
  "Cortaderia_selloana",
  "Festuca_bromoides",
  "Cynodon_dactylon",
  "Poa_annua",
  "Festuca_microstachys",
  "Polypogon_viridis",
  "Crypsis_schoenoides",
  "Polypogon_interruptus",
  "Hordeum_brachyantherum",
  "Bromus_madritensis",
  "Elymus_triticoides"
)

grassland <- veg |> 
  # keep only NCOS Mesa grassland transects and only grass species
  filter(
    str_detect(transect_name, "GL"),
    site == "ncos",
    psoc %in% poaceae_species
  )
```

# 3.  Code wrangling pseudocode

- 1. filter by ncos and GL
- 2. filter by poaceae species (grasses)
- 3. 